server {
    listen 8080;
    server_name localhost;

    # 1. Servir los archivos de React
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html; 
    }

    # 2. Enviar peticiones de despachos al microservicio ms-despachos
    location /api/v1/despachos {
        proxy_pass http://innova_ms_despachos:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Enviar peticiones de ventas al microservicio ms-ventas
    location /api/v1/ventas {
        proxy_pass http://innova_ms_ventas:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}